/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.DatabasController;
import Controller.ModelController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author petter
 */
public class CaseAndTask extends javax.swing.JFrame {

    static ModelController mc = new ModelController();
    /**
     * Creates new form ArendeAndTask
     */
    public CaseAndTask() {
        initComponents();
        loadMeny();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        meny = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        registerCase1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        registerCase2 = new javax.swing.JPanel();
        registerCase3 = new javax.swing.JPanel();
        certifyTask1 = new javax.swing.JPanel();
        certifyTask2 = new javax.swing.JPanel();
        modifyCase1 = new javax.swing.JPanel();
        modifyCase2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Välkommen till Fiktiv ABs ärendehanteringssystem.");

        jButton1.setText("Registrera ärende");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Uppdatera ärende");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Attestera arbetsuppgift");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menyLayout = new javax.swing.GroupLayout(meny);
        meny.setLayout(menyLayout);
        menyLayout.setHorizontalGroup(
            menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menyLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(menyLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        menyLayout.setVerticalGroup(
            menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menyLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Registrera ärende");

        jLabel3.setText("Ärende nr:");

        jLabel4.setText("---");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("Instruktioner:");

        jLabel6.setText("Kategori:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nätverk", "Applikationer", "Säkerhet", "Användare" }));

        jButton4.setText("Avbryt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Nästa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerCase1Layout = new javax.swing.GroupLayout(registerCase1);
        registerCase1.setLayout(registerCase1Layout);
        registerCase1Layout.setHorizontalGroup(
            registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCase1Layout.createSequentialGroup()
                .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerCase1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerCase1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jLabel2)))
                    .addGroup(registerCase1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(registerCase1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(registerCase1Layout.createSequentialGroup()
                                    .addComponent(jButton4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        registerCase1Layout.setVerticalGroup(
            registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCase1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout registerCase2Layout = new javax.swing.GroupLayout(registerCase2);
        registerCase2.setLayout(registerCase2Layout);
        registerCase2Layout.setHorizontalGroup(
            registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        registerCase2Layout.setVerticalGroup(
            registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout registerCase3Layout = new javax.swing.GroupLayout(registerCase3);
        registerCase3.setLayout(registerCase3Layout);
        registerCase3Layout.setHorizontalGroup(
            registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        registerCase3Layout.setVerticalGroup(
            registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout certifyTask1Layout = new javax.swing.GroupLayout(certifyTask1);
        certifyTask1.setLayout(certifyTask1Layout);
        certifyTask1Layout.setHorizontalGroup(
            certifyTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        certifyTask1Layout.setVerticalGroup(
            certifyTask1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout certifyTask2Layout = new javax.swing.GroupLayout(certifyTask2);
        certifyTask2.setLayout(certifyTask2Layout);
        certifyTask2Layout.setHorizontalGroup(
            certifyTask2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        certifyTask2Layout.setVerticalGroup(
            certifyTask2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout modifyCase1Layout = new javax.swing.GroupLayout(modifyCase1);
        modifyCase1.setLayout(modifyCase1Layout);
        modifyCase1Layout.setHorizontalGroup(
            modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        modifyCase1Layout.setVerticalGroup(
            modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout modifyCase2Layout = new javax.swing.GroupLayout(modifyCase2);
        modifyCase2.setLayout(modifyCase2Layout);
        modifyCase2Layout.setHorizontalGroup(
            modifyCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        modifyCase2Layout.setVerticalGroup(
            modifyCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(meny, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registerCase1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registerCase2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registerCase3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(certifyTask1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(certifyTask2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(modifyCase1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(modifyCase2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(meny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(modifyCase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(modifyCase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(certifyTask1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(certifyTask2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(meny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(modifyCase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(modifyCase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(certifyTask1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(certifyTask2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jMenu2.setText("File");

        jMenuItem1.setText("Meny");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Registrera ärende");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Uppdatera ärende");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Attestera arbetsuppgift");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Avsluta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //registrera ärende-knappen på menysidan
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadRegisterCase1();    
    }//GEN-LAST:event_jButton1ActionPerformed
    //Updatera ärendeknappen på menysidan
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loadUpdateCase1();
    }//GEN-LAST:event_jButton2ActionPerformed
    //Attestera arbetsuppgift på menysidan
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        loadCertifyTask1();
    }//GEN-LAST:event_jButton3ActionPerformed
    //Menyknappen i menyn
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    loadMeny();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //Registrera ärende i menyn
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        loadRegisterCase1();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    //Avslutaknappen i menyn
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    //Avbrytknapp på registerCase1
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        meny.setVisible(true);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
    //uppdatera ärende i menyn
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(true);
        modifyCase2.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    //attestera arbetsuppgift i menyn
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(true);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    //Nästa knappen på RegisterCase1
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            DatabasController cc;   
            cc = new DatabasController();
            
            String arendeNr = jLabel4.getText();
            String instructions = jTextArea1.getText();
            String category = (String)jComboBox1.getSelectedItem();
            String caseStatus = "Aktiv";
            mc.regCase(arendeNr, instructions, category, caseStatus);
            cc.saveCaseToDatabase(arendeNr, instructions, category, caseStatus);
            registerCase1.setVisible(false);
            registerCase2.setVisible(true);
            jTextArea1.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(RegisterCase1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void loadRegisterCase1(){
        meny.setVisible(false);
        registerCase1.setVisible(true);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(false); 
        
        //Skriver ut nästa ärendenumret på skärmen
        try {
            DatabasController cc = new DatabasController();
            int nextNr = cc.getNewCaseNr();
            String arendeNr = Integer.toString(nextNr);
            jLabel4.setText(arendeNr);
             
                  
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att hämta nytt nr.");
                System.out.println(ex.getMessage());
            
        }
    }
        
    private void loadRegisterCase2(){
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(true);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(false);   
    }
    
    private void loadRegisterCase3(){
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(true);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(false);         
    }
    
    private void loadCertifyTask1(){
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(true);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(false);         
    }
    
    private void loadCertifyTask2(){
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(true);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(false);         
    }
    
    private void loadUpdateCase1(){
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(true);
        modifyCase2.setVisible(false);         
    }
    
    private void loadUpdateCase2(){
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(true);         
    }
    
    private void loadMeny(){
        meny.setVisible(true);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        certifyTask1.setVisible(false);
        certifyTask2.setVisible(false);
        modifyCase1.setVisible(false);
        modifyCase2.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaseAndTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaseAndTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaseAndTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaseAndTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaseAndTask().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel certifyTask1;
    private javax.swing.JPanel certifyTask2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel meny;
    private javax.swing.JPanel modifyCase1;
    private javax.swing.JPanel modifyCase2;
    private javax.swing.JPanel registerCase1;
    private javax.swing.JPanel registerCase2;
    private javax.swing.JPanel registerCase3;
    // End of variables declaration//GEN-END:variables
}
